# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
        migrations.RenameModel(
            old_name='Slot',
            new_name='Slots',
        ),
    ]
