# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20170830_2345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
