# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20170830_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='slot',
            new_name='event',
        ),
    ]
