# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20170831_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
