# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_auto_20170901_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Slot'),
        ),
    ]
